# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('budgets', '0001_initial'),
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        ('moods', '0001_initial'),
        ('occasions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Ex : "Indoor / Outdoor"', max_length=100, verbose_name='Question')),
                ('option_a', models.CharField(max_length=50, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=50, verbose_name='Option B')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Question de préférence',
                'verbose_name_plural': 'Questions de préférence',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Petite attention',
                'verbose_name_plural': 'Petites attentions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time_value', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('personal_message', models.TextField(blank=True, verbose_name='Message personnel')),
                ('current_step', models.CharField(choices=[('mood', 'mood'), ('city', 'city'), ('place', 'place'), ('activity', 'activity'), ('budget', 'budget'), ('schedule', 'schedule'), ('final', 'final')], default='mood', max_length=20, verbose_name='Étape courante')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('completed', 'Complété')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le (autosave)')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity', verbose_name='Activité')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.budget', verbose_name='Budget')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='Ville')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_plans', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moods.mood', verbose_name='Ambiance')),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='occasions.occasion', verbose_name='Occasion')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.place', verbose_name='Lieu')),
                ('special_attentions', models.ManyToManyField(blank=True, related_name='date_plans', to='planner.specialattention', verbose_name='Petites attentions')),
            ],
            options={
                'verbose_name': 'Rendez-vous en construction',
                'verbose_name_plural': 'Rendez-vous en construction',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DatePlanPreferenceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('a', 'Option A'), ('b', 'Option B')], max_length=1)),
                ('date_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_answers', to='planner.dateplan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='planner.preferencequestion')),
            ],
            options={
                'verbose_name': 'Réponse de préférence',
                'verbose_name_plural': 'Réponses de préférence',
                'unique_together': {('date_plan', 'question')},
            },
        ),
    ]
