# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_place_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Ex : Gérant, Propriétaire...', max_length=100, verbose_name='Rôle')),
                ('proof_details', models.TextField(blank=True, help_text="Éléments permettant de vérifier le lien avec l'établissement (numéro de téléphone pro, etc.).", verbose_name='Justificatif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='catalog.place', verbose_name='Lieu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_claims', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur·se')),
            ],
            options={
                'verbose_name': 'Revendication de lieu',
                'verbose_name_plural': 'Revendications de lieux',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('place', 'user'), name='unique_place_claim_per_user')],
            },
        ),
    ]
