# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('viewed', 'Vue'), ('accepted', 'Acceptée'), ('maybe', 'Peut-être'), ('declined', 'Déclinée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('partner_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du partenaire')),
                ('partner_reply_message', models.TextField(blank=True, verbose_name='Message de réponse')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Première vue le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('date_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='planner.dateplan', verbose_name='Rendez-vous')),
                ('partner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Compte du partenaire')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
