# Generated by Django 6.1.1 on 2026-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Coché automatiquement par la commande send_date_reminders.', verbose_name='Rappel envoyé'),
        ),
    ]
