# Generated by Django 6.1.1 on 2026-09-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de l'acceptation des CGU à l'inscription.", null=True, verbose_name='CGU acceptées le'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text="Invitation acceptée/déclinée, nouveau message... en plus des notifications dans l'application.", verbose_name='Recevoir les notifications par e-mail'),
        ),
    ]
