# Generated by Django 6.1.1 on 2026-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accepted_terms_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_verified',
            field=models.BooleanField(default=False, verbose_name='Identité vérifiée (selfie)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mis à jour automatiquement par Subscription.activate().', verbose_name='Compte Premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text="Photo privée utilisée uniquement pour la vérification manuelle d'identité — jamais affichée publiquement.", null=True, upload_to='verification/', verbose_name='Photo de vérification'),
        ),
    ]
