# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Jeton')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du proche prévenu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière position le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to='planner.dateplan', verbose_name='Rendez-vous concerné')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to=settings.AUTH_USER_MODEL, verbose_name='Partagé par')),
            ],
            options={
                'verbose_name': 'Partage de position',
                'verbose_name_plural': 'Partages de position',
                'ordering': ['-created_at'],
            },
        ),
    ]
