# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('budgets', '0001_initial'),
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Image')),
                ('price_estimate', models.PositiveIntegerField(default=0, verbose_name='Prix estimé (Ar)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='activities.activity', verbose_name='Activité')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.budget', verbose_name='Budget')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='locations.city', verbose_name='Ville')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moods.mood', verbose_name='Ambiance')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='catalog.place', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-is_featured', 'display_order', 'name'],
            },
        ),
    ]
