# Generated by Django 5.0.14 on 2026-09-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Date With U', max_length=100, verbose_name='Nom du site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('default_currency', models.CharField(default='MGA', max_length=10, verbose_name='Devise par défaut')),
                ('invitation_expiration_days', models.PositiveIntegerField(default=7, verbose_name='Expiration des invitations (jours)')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='Inscriptions activées')),
                ('chat_enabled', models.BooleanField(default=False, verbose_name='Chat activé')),
                ('reviews_enabled', models.BooleanField(default=False, verbose_name='Avis activés')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
