# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Accroche')),
                ('content', models.TextField(help_text='Markdown simple (titres ##, listes -, gras **texte**).', verbose_name='Contenu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image de couverture')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='locations.city', verbose_name='Ville concernée')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
