# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('price', models.PositiveIntegerField(verbose_name='Prix (Ar / mois)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Durée (jours)')),
                ('max_active_dates', models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité (formule Premium).', null=True, verbose_name='Rendez-vous actifs simultanés')),
                ('perks', models.TextField(blank=True, help_text='Un avantage par ligne, affiché sur la page tarifs.', verbose_name='Avantages')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Formule Premium',
                'verbose_name_plural': 'Formules Premium',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('active', 'Active'), ('expired', 'Expirée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandée le')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activée le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('payment_reference', models.CharField(blank=True, help_text="Ex : référence de transfert Mobile Money, à vérifier manuellement pour l'instant.", max_length=120, verbose_name='Référence de paiement')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='premium.premiumplan', verbose_name='Formule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-requested_at'],
            },
        ),
    ]
