# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_place_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('description', models.CharField(help_text="Ex : -15% sur l'addition, boisson offerte...", max_length=255, verbose_name='Description')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Réduction (%)')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name='Utilisations max')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Utilisations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('place', models.ForeignKey(blank=True, help_text='Laisser vide pour un code valable sur tous les lieux.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='catalog.place', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-valid_from'],
            },
        ),
    ]
