# Generated by Django 5.0.14 on 2026-09-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Occasion',
                'verbose_name_plural': 'Occasions',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
