# Generated by Django 5.0.14 on 2026-09-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Nom')),
                ('min_amount', models.PositiveIntegerField(default=0, verbose_name='Montant minimum (Ar)')),
                ('max_amount', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un budget sans plafond (ex : Luxe, 150 000 Ar+).', null=True, verbose_name='Montant maximum (Ar)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['display_order', 'min_amount'],
            },
        ),
    ]
