# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji / icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('price_min', models.PositiveIntegerField(default=0, verbose_name='Prix minimum (Ar)')),
                ('price_max', models.PositiveIntegerField(default=0, verbose_name='Prix maximum (Ar)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image principale')),
                ('opening_hours', models.JSONField(blank=True, help_text='Ex : {"mon": "09:00-18:00", "sat": "10:00-16:00"}', null=True, verbose_name='Horaires')),
                ('available_days', models.JSONField(blank=True, help_text='Liste de codes jours, ex : ["mon", "tue", "sat"]. Codes valides : mon, tue, wed, thu, fri, sat, sun', null=True, verbose_name='Jours disponibles')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Lieu recommandé')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Lieu populaire')),
                ('is_new', models.BooleanField(default=False, verbose_name='Nouveau lieu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('category', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='catalog.category', verbose_name='Catégorie')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='locations.city', verbose_name='Ville')),
                ('subcategory', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_as_subcategory', to='catalog.category', verbose_name='Sous-catégorie')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['-is_recommended', '-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Légende')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.place', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Image de lieu',
                'verbose_name_plural': 'Galerie de lieux',
                'ordering': ['display_order'],
            },
        ),
    ]
