# Generated by Django 6.1.1 on 2026-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Incrémenté à chaque consultation du détail — utilisé pour les stats partenaires.', verbose_name='Nombre de vues'),
        ),
    ]
