# Generated by Django 6.1.1 on 2026-09-19 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_place_view_count'),
        ('locations', '0001_initial'),
        ('moods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_conversations_as_author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur·e du post')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_conversations_as_requester', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur·se')),
            ],
            options={
                'verbose_name': 'Conversation (fil public)',
                'verbose_name_plural': 'Conversations (fil public)',
            },
        ),
        migrations.CreateModel(
            name='FeedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='feed.feedconversation', verbose_name='Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur·rice')),
            ],
            options={
                'verbose_name': 'Message (fil public)',
                'verbose_name_plural': 'Messages (fil public)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=500, verbose_name='Message')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Date envisagée')),
                ('time_value', models.TimeField(blank=True, null=True, verbose_name='Heure envisagée')),
                ('is_active', models.BooleanField(default=True, help_text="Décoché automatiquement une fois que l'auteur·e a trouvé quelqu'un (ou manuellement).", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur·e')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='locations.city', verbose_name='Ville')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='moods.mood', verbose_name='Ambiance')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='catalog.place', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedconversation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='feed.post', verbose_name='Post'),
        ),
        migrations.CreateModel(
            name='PostInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Déclinée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='feed.post', verbose_name='Post')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_interests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur·se')),
            ],
            options={
                'verbose_name': 'Demande de discussion',
                'verbose_name_plural': 'Demandes de discussion',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'requester')},
            },
        ),
        migrations.AddField(
            model_name='feedconversation',
            name='interest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='feed.postinterest', verbose_name="Demande d'origine"),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Le')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
