# Generated by Django 5.2.17 on 2026-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo optionnelle jointe à la publication.', null=True, upload_to='feed/posts/%Y/%m/', verbose_name='Photo'),
        ),
    ]
