# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, help_text='Réponse publique du/de la partenaire ayant revendiqué ce lieu (voir apps.partners).', verbose_name='Réponse du gérant'),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Répondu le'),
        ),
        migrations.CreateModel(
            name='DateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
                ('date_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ratings', to='planner.dateplan', verbose_name='Rendez-vous')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur noté')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Noté par')),
            ],
            options={
                'verbose_name': 'Note de rendez-vous',
                'verbose_name_plural': 'Notes de rendez-vous',
                'ordering': ['-created_at'],
                'unique_together': {('date_plan', 'rater', 'rated_user')},
            },
        ),
    ]
