# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Image')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text="Durée approximative de l'activité.", null=True, verbose_name='Durée (minutes)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Prix (Ar)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='catalog.category', verbose_name='Catégorie')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='locations.city', verbose_name='Ville')),
                ('compatible_budgets', models.ManyToManyField(blank=True, related_name='activities', to='budgets.budget', verbose_name='Budgets compatibles')),
                ('compatible_moods', models.ManyToManyField(blank=True, related_name='activities', to='moods.mood', verbose_name='Moods compatibles')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='catalog.place', verbose_name='Lieu associé')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['name'],
            },
        ),
    ]
