# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('invitation_viewed', 'Invitation vue'), ('invitation_accepted', 'Invitation acceptée'), ('invitation_maybe', 'Invitation en peut-être'), ('invitation_declined', 'Invitation déclinée'), ('system', 'Système')], default='system', max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('link', models.CharField(blank=True, help_text='Chemin relatif, ex: /dashboard/', max_length=255, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
