# Generated by Django 5.0.14 on 2026-09-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='planner.dateplan', verbose_name='Rendez-vous')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_creator', models.BooleanField(verbose_name='Envoyé par le créateur du rendez-vous')),
                ('sender_label', models.CharField(blank=True, max_length=100, verbose_name="Nom affiché de l'expéditeur")),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu par le destinataire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
